dist: trusty

language: cpp

cache: ccache

compiler:
  - gcc
  - clang

git:
    depth: 3

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-test-dev
      - flex
      - valgrind
      - lcov

script:
  - ./build-and-install-poco.bash $HOME/poco-1.7.7
  - cmake -DCMAKE_PREFIX_PATH=$HOME/poco-1.7.7 -DBUILD_TESTING=ON -DBUILD_COVERAGE=ON
  - make -j $(nproc)
  - env
  - [[ "$CXX" =~ "gcc"   ]] && ./lcov.bash
  - [[ "$CXX" =~ "clang" ]] && make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
