dist: xenial

language: cpp

cache: ccache

compiler:
    - clang
    - gcc

git:
    depth: 3


addons:
    apt:
        packages:
            - libboost-dev
            - libboost-test-dev
            - flex
            - valgrind
            - lcov

script: ./build-and-test.bash

after_success:
  - bash <(curl -s https://codecov.io/bash)
