language: cpp

cache: ccache

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-4.9
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-4.9]

    - os: linux
      dist: trusty
      compiler: clang

    - os: osx
      compiler:
        - clang

git:
  depth: 1

addons:
  apt:
    packages:
      - build-essential
      - curl
      - flex
      - gcc
      - lcov
      - libboost-dev
      - libboost-test-dev
      - libssl-dev
      - python3
      - python3-dev
      - valgrind
      - wget

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install openssl poco flex ccache;
    else
      sudo sh -x scripts/ubuntu-prerequisites.sh;
    fi

install:
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

script:
  - cmake --version
  - ccache -s
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cmake -DBUILD_SWIG=ON -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include/ -DPoco_LIBRARIES='/usr/local/opt/poco/lib/libPocoFoundation.dylib;/usr/local/opt/poco/lib/libPocoCrypto.dylib;/usr/local/opt/poco/lib/libPocoNet.dylib;/usr/local/opt/poco/lib/libPocoNetSSL.dylib';
    else
      cmake -DBUILD_SWIG=ON -DBUILD_COVERAGE=ON -DBUILD_POCO=ON;
      export LD_LIBRARY_PATH=$PWD/lib:$PWD/thirdparty/lib:$PWD/python:$LD_LIBRARY_PATH;
    fi
  - export PYTHONPATH=$PWD/lib:$PWD/python;
  - make
  - make test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      make NightlyMemCheck;
      if [ "$CXX" == "g++" ]; then make NightlyCoverage; fi;
    fi
  - ccache -s

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
