dist: trusty

language: cpp
compiler:
    - clang
    - gcc

git:
    depth: 3


addons:
    apt:
        packages:
            - libboost-dev
            - libboost-test-dev
            - flex


script: mkdir build && cd build && cmake -DBUILD_TESTING=ON .. && make -j2 && make -j2 test
