dist: trusty

language: cpp
compiler:
    - clang
    - gcc

git:
    depth: 3


addons:
    apt:
        packages:
            - libboost-dev
            - libboost-test-dev
            - flex


script: bash travis.sh
